# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-16 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=16)),
                ('office', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=10)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sign.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('work_id', models.IntegerField(unique=True)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
